apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-helm-values
  namespace: ingress-nginx
data:
  replicaCount: "2"
  cpuRequest: "500m"
  memoryRequest: "512Mi"
  cpuLimit: "1000m"
  memoryLimit: "1Gi"
  autoscalingEnabled: "false"
  serviceMonitorEnabled: "true"
