apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-helm-values
  namespace: ingress-nginx
data:
  replicaCount: "2"
  cpuRequest: "200m"
  memoryRequest: "256Mi"
  cpuLimit: "500m"
  memoryLimit: "512Mi"
  autoscalingEnabled: "false"
  serviceMonitorEnabled: "false"
