apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - name: hello-app
          image: nginxdemos/hello:0.2
          ports:
            - containerPort: 80
          env:
            - name: APP_VERSION
              value: "v1.0"